[package]
name = "flip_on_me"
version = "3.0.0-rc"
authors = ["Brushfam <green@727.ventures>"]
edition = "2021"

[dependencies]
ink = { version = "~4.0.0-rc", default-features = false}

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }

flipper = { path = "../..", default-features = false }
openbrush = { path = "../../../..", default-features = false }

[lib]
name = "flip_on_me"
path = "lib.rs"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
]

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "flipper/std",
    "openbrush/std",
]
ink-as-dependency = []

[profile.dev]
codegen-units = 16
