[package]
name = "flash_borrower"
version = "1.2.0"
authors = ["Supercolony <dominik.krizo@supercolony.net>"]
edition = "2021"

[dependencies]
ink_primitives = { branch = "master", git = "https://github.com/Supercolony-net/ink", default-features = false }
ink_metadata = { branch = "master", git = "https://github.com/Supercolony-net/ink", default-features = false, features = ["derive"], optional = true }
ink_env = { branch = "master", git = "https://github.com/Supercolony-net/ink", default-features = false }
ink_storage = { branch = "master", git = "https://github.com/Supercolony-net/ink", default-features = false }
ink_lang = { branch = "master", git = "https://github.com/Supercolony-net/ink", default-features = false }
ink_prelude = { branch = "master", git = "https://github.com/Supercolony-net/ink", default-features = false }

scale = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
scale-info = { version = "1", default-features = false, features = ["derive"], optional = true }

# These dependencies
brush = { path = "../..", default-features = false, features = ["psp22"] }

[lib]
name = "flash_borrower"
path = "lib.rs"
crate-type = [
    "cdylib",
]

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info",
    "scale-info/std",
    "brush/std",
]
ink-as-dependency = []

[profile.dev]
codegen-units = 16
overflow-checks = false

[profile.release]
overflow-checks = false
