[package]
name = "proc_macros"
version = "1.0.0"
authors = ["Supercolony <green.baneling@supercolony.net>"]
edition = "2018"

[dependencies]
syn = { version = "1.0", features = ["parsing", "full", "visit", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1"
serde_json = "1.0.64"
fs2 = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
cargo_metadata = "0.13.1"
unwrap = "1.2.1"
blake2 = "0.9"
ink_lang_ir = { git = "https://github.com/Supercolony-net/ink", branch = "feature/recovery", default-features = false }

[dev-dependencies]
ink_primitives = { git = "https://github.com/Supercolony-net/ink", branch = "feature/recovery", default-features = false }
ink_metadata = { git = "https://github.com/Supercolony-net/ink", branch = "feature/recovery", default-features = false, features = ["derive"] }
ink_env = { git = "https://github.com/Supercolony-net/ink", branch = "feature/recovery", default-features = false }
ink_lang = { git = "https://github.com/Supercolony-net/ink", branch = "feature/recovery", default-features = false }
ink_storage = { git = "https://github.com/Supercolony-net/ink", branch = "feature/recovery", default-features = false }
ink_prelude = { git = "https://github.com/Supercolony-net/ink", branch = "feature/recovery", default-features = false }

scale = { package = "parity-scale-codec", version = "2.1", default-features = false, features = ["derive"] }
scale-info = { version = "0.6.0", default-features = false, features = ["derive"] }

brush = { path = "..", default-features = false }

[lib]
name = "proc_macros"
path = "lib.rs"
proc-macro = true

[features]
default = ["std"]
std = [
    "ink_lang_ir/std",
]