[package]
name = "brush_derive"
version = "1.2.0"
authors = ["Supercolony <green.baneling@supercolony.net>"]
edition = "2021"

[lib]
name = "brush_derive"
path = "lib.rs"
crate-type = [
    "rlib",
]

[features]
default = ["std"]
std = []