[package]
name = "my_psp22_metadata_upgradeable"
version = "1.5.0"
authors = ["Supercolony <horacio.lex@supercolony.net>"]
edition = "2021"

[dependencies]
ink_primitives = { rev = "c974cde", git = "https://github.com/paritytech/ink", default-features = false }
ink_metadata = { rev = "c974cde", git = "https://github.com/paritytech/ink", default-features = false, features = ["derive"], optional = true }
ink_env = { rev = "c974cde", git = "https://github.com/paritytech/ink", default-features = false }
ink_storage = { rev = "c974cde", git = "https://github.com/paritytech/ink", default-features = false }
ink_lang = { rev = "c974cde", git = "https://github.com/paritytech/ink", default-features = false }
ink_prelude = { rev = "c974cde", git = "https://github.com/paritytech/ink", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

# These dependencies
brush = { path = "../../..", default-features = false, features = ["psp22", "ownable"] }

[lib]
name = "my_psp22_metadata_upgradeable"
path = "lib.rs"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
]

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info",
    "scale-info/std",

    # These dependencies
    "brush/std",
]
ink-as-dependency = []

[profile.dev]
codegen-units = 16
overflow-checks = false

[profile.release]
overflow-checks = false
