[package]
name = "my_psp22_metadata"
version = "3.0.0-beta.1"
authors = ["Brushfam <m.konstantinovna@727.ventures>"]
edition = "2021"

[dependencies]
ink = { version = "4.0.0-beta.1", default-features = false}

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }

# These dependencies
openbrush = { path = "../../..", default-features = false, features = ["psp22"] }

[lib]
name = "my_psp22_metadata"
path = "lib.rs"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
]

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    # These dependencies
    "openbrush/std",
]
ink-as-dependency = []

[profile.dev]
codegen-units = 16
