[package]
name = "brush_derive_macro"
version = "1.0.0"
authors = ["Supercolony <green.baneling@supercolony.net>"]
edition = "2021"

[lib]
name = "brush_derive_macro"
path = "lib.rs"
crate-type = [
    "rlib",
]

[features]
default = ["std"]
std = []